### ISSUE TITLE
Simple 301 Does Not Propagate To Load Balanced Servers

### ISSUE THREAD

**Issue by necoras** [wkallhof/Simple301#18]
We have a load balanced environment using [Flexible Load Balancing](https://our.umbraco.org/documentation/getting-started/setup/server-setup/load-balancing/flexible). Redirects created on the back office server do not propagate to the front end (public) servers. We have to manually login to each server and add each redirect multiple times. This quickly becomes unworkable with either large numbers of redirects, and/or large numbers of front end servers.

**Comment by wkallhof** [comment]
@necoras , Technically what I think is happening is that the in-memory cache of the redirects is not being shared between the front end servers. If it truly follows the Flexible Load Balancing strategy, there is a single database as the source of truth for CMS data, and the front end servers are pointing at a single database. Persisted redirects from Simple 301 are stored in the database, so the solve is not logging into each front end server and adding them, as this will result in duplicate redirects persisted to the database.

The problem here is that each instance has it's own in-memory collection of redirects, and the way Simple 301 is architected is to first look at the in memory collection for performance reasons, but in retrospect, this is admittedly not scalable to multiple instances in a load balanced environment. I will need to build in some way to invalidate that in-memory collection. In order to avoid having any manual process, I think it would be a duration based in-memory cache. You could configure the in-memory cache duration in the web.config, and it would eventually invalidate itself, where it would go out to the database to fetch the entire collection again, caching once more for the specified time.

I should have something developed for that in the coming weeks ( I am actively developing websites with Simple 301 and we are in load balanced environments, so I need to solve this ). Thanks for pointing this issue out.

**Comment by necoras** [comment]
@wkallhof Thanks for the update. One further point: _do not_ create redirects on the front end servers. You were correct that this results in duplicate redirects in the database... eventually. It seemed to occur when the caches were updated; certainly it wasn't until several hours after the initial redirect creation. When that occurred it caused _every_ page to stop responding. That's probably an additional issue: when duplicate redirects exist Simple 301 should either pick one or refuse to do the redirect at all. Currently it just takes down the whole site.

We ended up rolling back to before Simple 301 was installed. We may investigate using it again once it supports Load Balanced setups.

Thanks again.

**Comment by leethomascook** [comment]
We just hit this issue as well. Be good to get a fix.

**Comment by wkallhof** [comment]
@necoras @leethomascook I just release v1.1.2 which re-architects how redirects are managed and persisted. The back-office will always pull from the database, not an in-memory collection. It now utilizes web cache to hold on to redirects vs a pure in-memory collection. That cache is invalidated after a specified period of time (see readme on how to manage those settings). This way your load balanced instances can still take advantage of caching while also syncing up with the database after the cache expires. You can now manually clear the cache per instance if needed by logging into each machine and clicking the "Clear cache" button in the top right section of where you manage redirects (it shouldn't be required but can be useful for troubleshooting redirects if needed). You shouldn't see inconsistent back-office redirect results now. 

Please test out and re-open if you find any issues.
