### ISSUE TITLE
Missing tab after Upgrade

### ISSUE THREAD

**Issue by jonathanS8080** [wkallhof/Simple301#20]
Hi,
Each time we upgrade Umbraco we have to resinstall Simple 301 - is this a known issue?

Jon

**Comment by wkallhof** [comment]
@jonathanS8080,

This was because when you updated Umbraco, Umbraco would clear out it's dashboard.config sections, where at the time, I was storing the reference to the Redirect Manger tab.

In the latest version v1.1.4: https://github.com/wkallhof/Simple301/commit/f1d2d0dd9ba900720bd96c4a440a6742228e7313 I have updated it to install into its own section so it should no longer be a problem when upgrading.
